version: '2'
services:
  db-discord:
    container_name: db-discord
    hostname: db-discord
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    networks:
      - discord
    environment:
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
      POSTGRES_DB: discord
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/discord-bot/postgresData/data:/var/lib/postgresql/data
    restart: always

  discord-bot:
    image: andreichenko/discord-bot:master
    hostname: discord-bot
    container_name: discord-bot
    networks:
      - discord
    environment:
      - YOUTUBE_API_KEY=****KEY****
      - DISCORD_BOT_KEY=****KEY****
      - BOT_USER_ID=1234
      - OWNER_ID=12345
      - POSTGRES_LOCATION=jdbc:postgresql://db-discord:5432/postgres
    restart: always

networks:
  discord:
    driver: bridge