version: '2'
services:

  db-discord:
    container_name: discord-bot-db
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
      POSTGRES_DB: discord
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/discord-bot/postgresData:/var/lib/postgresql